In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3],dtype=np.float64)#生成指定的类型的数组
print(arr.dtype)

float64


In [3]:
arr

array([ 1.,  2.,  3.])

In [4]:
int_arr = np.array([1,2,3,4,5])
print (int_arr,int_arr.dtype)

[1 2 3 4 5] int64


In [5]:
#使用astype复制数组并转换数据类型
float_arr = int_arr.astype(np.float)
print (float_arr,float_arr.dtype)

[ 1.  2.  3.  4.  5.] float64


使用astype将float转换为int时，小数部分会被舍弃

使用astype把字符串转换成数组的时候，如果失败抛出异常。

In [6]:
str_arr = np.array(['1.2','2.f'],dtype=np.string_)
str_arr

array([b'1.2', b'2.f'],
      dtype='|S3')

In [7]:
float_arr = str_arr.astype(np.float)
print (float_arr,float_arr.dtype)

ValueError: could not convert string to float: '2.f'

## 取值

In [ ]:
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print (a)
print (a.shape)

In [8]:
#切片
b = a[0:2,2:4] #0：2指的是行的取值0,1；2：4指的是列的取值2,3；因此是[3,4][7,8]
b

NameError: name 'a' is not defined

In [9]:
#如果修改参数，那么会修改，因为numpy是引用传值,如果是要不想改变原值用copy()
b[0,0] = 1111
print (b)
print (a)

NameError: name 'b' is not defined

In [10]:
row_r1 = a[1,:]#找到第二行
print(row_r1,row_r1.shape)

NameError: name 'a' is not defined

In [11]:
col_r1 = a[:,1].copy()
print(col_r1,col_r1.shape)#是一个一维数组

NameError: name 'a' is not defined

In [12]:
col_r2 = a[:,1:2]
print(col_r2,col_r2.shape)

NameError: name 'a' is not defined

In [13]:
print (a)
d = a[[0,1,2],[0,1,0]]#取出各个位置的值，(0,0),(1,1),(2,0)坐标
print (d.shape) #三维数组

NameError: name 'a' is not defined

In [14]:
print (np.array([a[0,0],a[1,1],a[2,0]])) #取出3个值组成3维数组。

NameError: name 'a' is not defined

In [15]:
print (a)
print(a[[0,0],[1,0]]) #(0,1),(0,0)坐标
print(np.array([a[0,0],a[0,1]]))#（0,0),(0,1)坐标

NameError: name 'a' is not defined

In [16]:
print (a)
b = np.array([0,2,1])
a[np.arange(3),b] #选择0-2行，列0，2，1

NameError: name 'a' is not defined

In [17]:
a[np.arange(3),b] += 10 #所选中的位置+10
print (a)

NameError: name 'a' is not defined

In [18]:
bool_index = (a > 2)#可以利用数组判断,挑选符合条件的元素
print (bool_index)

NameError: name 'a' is not defined

In [19]:
print (a[a>2])#取出大于2的元素，组成新数组

NameError: name 'a' is not defined

## 求值运算

In [20]:
x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)

In [21]:
print (x)
print (y)

[[ 1.  2.]
 [ 3.  4.]]
[[ 5.  6.]
 [ 7.  8.]]


In [22]:
print (x.shape)
print (y.shape)

(2, 2)
(2, 2)


In [23]:
print (x + y) #逐元素求和

[[  6.   8.]
 [ 10.  12.]]


In [24]:
x-y #逐元素做差

array([[-4., -4.],
       [-4., -4.]])

In [25]:
#或者调用方法
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

逐个元素相乘

In [26]:
x/y #逐个元素相除

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

In [27]:
np.divide(x,y)#逐个元素相除

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

In [28]:
np.sqrt(x) #逐元素开方

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [29]:
v = np.array([9,10])
w = np.array([10,11])
print (v.shape)

(2,)


求向量内积

In [30]:
v.dot(w) #9*10 + 10 *11

200

In [31]:
np.dot(v,w)

200

In [32]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print (x)
print (y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [33]:
print (x.dot(y)) #[[(1*5+2*7) ,(1*6 + 2*8)][(3 * 5 +4 *7),(3*6 +4*8)]]

[[19 22]
 [43 50]]


In [34]:
print (x.dot(v))#2X2 * 2X1 = 2X1

[29 67]


转置

In [35]:
x

array([[1, 2],
       [3, 4]])

In [36]:
x.T

array([[1, 3],
       [2, 4]])

In [37]:
#一维数组转置还是自己
v.shape

(2,)

In [38]:
v.T.shape

(2,)

In [39]:
#二维就不一样
w= np.array([[1,2,3]])
print(w,w.shape)

[[1 2 3]] (1, 3)


In [40]:
print(w.T)

[[1]
 [2]
 [3]]


In [41]:
arr = np.random.randn(6,3) #6X3的随机矩阵
arr

array([[ 0.25857571, -0.15306753,  0.38472972],
       [ 0.88227336,  1.00800704, -0.56533634],
       [-1.54096816,  1.4621387 , -0.31546223],
       [-0.43436745, -0.70207447,  1.61481342],
       [-0.96142199,  1.19171133,  1.12074492],
       [ 1.62684494, -0.3818875 ,  0.25209027]])

In [42]:
print(arr.T.dot(arr)) #$X^T x X$ 3X6 * 6X3 得到3x3矩阵

[[ 6.97948235 -2.86540189 -1.28200159]
 [-2.86540189  5.23627995 -0.98438716]
 [-1.28200159 -0.98438716  4.4943796 ]]


高维的tensor也可以转置

In [43]:
arr = np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [44]:
print(arr.transpose((1,0,2))) 

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


默认0，1，2；三维第二和第三交换行,transpose实际上就是把第二个维度放在最外面，第一个维度放到第二个维度，第三个维度保持不变

In [45]:
print(arr.transpose(0,2,1))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [46]:
print (arr.transpose(2,1,0))

[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


In [47]:
print (arr.swapaxes(1,2))#相当于（arr.transpose(0,2,1)）交换1，2

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [48]:
x = np.arange(24).reshape(2,3,4)
y = np.arange(8).reshape(4,2)
print (x)
print (y)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [49]:
print (np.matmul(x,y).shape)#这种情况同dot

(2, 3, 2)


In [50]:
print (x.dot(y).shape)

(2, 3, 2)


In [51]:
x = np.arange(24).reshape(2,3,4)
y =  np.arange(16).reshape(2,4,2)
print (x.dot(y).shape)#4被cancel掉了

(2, 3, 2, 2)


In [52]:
np.matmul(x,y).shape#这个需要区分开

(2, 3, 2)

In [53]:
x = np.array([[1,2],[3,4]])
print (x)

[[1 2]
 [3 4]]


In [54]:
print (np.sum(x))
print (x.sum())

10
10


In [55]:
print (x.sum(axis=0))#对列求和，相当于把第一维压平
print (x.sum(axis=1)) #对行求和

[4 6]
[3 7]


In [56]:
#求平均
print (np.mean(x))
print (np.mean(x,axis=0))
print (np.mean(x,axis=1))
print (x.mean(axis=0))
print (x.mean(axis=1))

2.5
[ 2.  3.]
[ 1.5  3.5]
[ 2.  3.]
[ 1.5  3.5]


In [57]:
print (x.cumsum(axis=0))
print (x.cumsum(axis=1))

[[1 2]
 [4 6]]
[[1 3]
 [3 7]]


In [58]:
print (x.cumprod(axis=0))
print (x.cumprod(axis=1))

[[1 2]
 [3 8]]
[[ 1  2]
 [ 3 12]]


## 数组排序

In [59]:
arr = np.random.randn(8) *10
arr

array([  3.56144311,   3.02624311,  -2.81489167,  -1.12818582,
        23.18170226,  -6.71386622,  -0.86633966,   1.08732893])

In [60]:
arr.sort()
print (arr)

[ -6.71386622  -2.81489167  -1.12818582  -0.86633966   1.08732893
   3.02624311   3.56144311  23.18170226]


In [61]:
#二维数组排序
arr = np.random.randn(5,3)*10
print (arr)

[[  0.21313362  -3.98443798  10.44714247]
 [ 13.55268855  -7.14920449   9.58088114]
 [-15.11762294  -1.43975415 -15.71070954]
 [ -0.62094832  -0.65329305  -3.82302093]
 [  9.60884015  -0.87452999  -8.35839186]]


In [62]:
arr.sort(1) #对第一维进行排序，相当于列排序
print (arr)
arr.sort()
print ()
print (arr)

[[ -3.98443798   0.21313362  10.44714247]
 [ -7.14920449   9.58088114  13.55268855]
 [-15.71070954 -15.11762294  -1.43975415]
 [ -3.82302093  -0.65329305  -0.62094832]
 [ -8.35839186  -0.87452999   9.60884015]]

[[ -3.98443798   0.21313362  10.44714247]
 [ -7.14920449   9.58088114  13.55268855]
 [-15.71070954 -15.11762294  -1.43975415]
 [ -3.82302093  -0.65329305  -0.62094832]
 [ -8.35839186  -0.87452999   9.60884015]]


In [63]:
large_arr = np.random.randn(1000)
large_arr.sort()
print (large_arr)
print (large_arr[int(0.05 * len(large_arr))]) #找到最大值

[ -2.97344454e+00  -2.92357359e+00  -2.68387981e+00  -2.46726443e+00
  -2.46513853e+00  -2.44370897e+00  -2.43522850e+00  -2.43226540e+00
  -2.30831607e+00  -2.22931320e+00  -2.20767246e+00  -2.17839596e+00
  -2.16122854e+00  -2.08014112e+00  -2.02718625e+00  -2.00074299e+00
  -2.00023103e+00  -1.96967482e+00  -1.92960616e+00  -1.92113358e+00
  -1.91399075e+00  -1.89286136e+00  -1.87352387e+00  -1.87321614e+00
  -1.86296690e+00  -1.84464791e+00  -1.81197709e+00  -1.75810066e+00
  -1.75770152e+00  -1.75516064e+00  -1.72139718e+00  -1.70059623e+00
  -1.68965407e+00  -1.68209022e+00  -1.67997850e+00  -1.67406200e+00
  -1.66284720e+00  -1.65946703e+00  -1.65804707e+00  -1.62520577e+00
  -1.62330679e+00  -1.60500409e+00  -1.59980210e+00  -1.59376164e+00
  -1.59265546e+00  -1.58955720e+00  -1.57877378e+00  -1.56896966e+00
  -1.56384784e+00  -1.56313668e+00  -1.55039347e+00  -1.54567832e+00
  -1.54248281e+00  -1.52123544e+00  -1.51570866e+00  -1.50590097e+00
  -1.50375532e+00  -1.50085848e+00

-1.55039347365


> 传播，如果是小的矩阵去和大的矩阵做一下操作，但是希望小矩阵能循环和大矩阵的那些块做一样的操作，那继续要Broadcasting（传播）.

In [64]:
#想给每一行都加上向量V就需要用到传播
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])


In [65]:
#如果不用传播
y = np.empty_like(x)
print (y)

[[                  0                   0                   6]
 [                  1                   0 3615946731872583680]
 [                  0 4120851028606320640                   0]
 [7378129167369371648                   0    1697633326661632]]


In [66]:
for i in range(4):
    y[i,:] = x[i,:] + v
print (y)
#效率不高

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [67]:
#所以用传播
x+v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

> 当操作两个arr的时候，numpy会逐个比较他们的shape,在下面情况下，两个arr会兼容和输出传播结果。
1. 相等
2. 其中一个为1，会拷贝到每一个，shape匹配

In [68]:
v = np.array([1,2,3])
w = np.array([4,5])
print (v.shape,w.shape) #无法传播相加

(3,) (2,)


In [69]:
v = v.reshape(3,1) #但是通过reshape可以相加
print (v.shape)

(3, 1)


In [70]:
v + w

array([[5, 6],
       [6, 7],
       [7, 8]])

In [71]:
x = np.array([[1,2,3],[4,5,6]]) #2X3的
w = np.array([4,5])

In [72]:
x + w

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [73]:
(x.T + w).T #可以转置相加后，在转置回来

array([[ 5,  6,  7],
       [ 9, 10, 11]])

## 逻辑运算

In [74]:
x_arr = np.array([1.1,1.2,1.3,1.4,1.5])
y_arr = np.array([2.1,2.2,2.3,2.4,2.5])

In [75]:
cond = np.array([True,False,True,True,False])
print (np.where(cond,x_arr,y_arr))

[ 1.1  2.2  1.3  1.4  2.5]


In [76]:
arr = np.random.randn(4,4)

In [77]:
print (arr > 0 )

[[ True  True False  True]
 [False  True False False]
 [False False False False]
 [ True  True  True  True]]


In [78]:
print (np.where(arr > 0,2,-1)) # true 用2 false 用-1

[[ 2  2 -1  2]
 [-1  2 -1 -1]
 [-1 -1 -1 -1]
 [ 2  2  2  2]]


In [79]:
print (np.where(arr > 0,1,arr)) #大于的用1表示，其他还是用原来的值

[[ 1.          1.         -0.86221399  1.        ]
 [-1.19212043  1.         -0.02073754 -0.89558906]
 [-1.37154216 -0.58042845 -0.94253905 -1.08640676]
 [ 1.          1.          1.          1.        ]]


## 高级的处理

In [80]:
arr = np.arange(8)
print (arr.shape)

(8,)


In [81]:
arr.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [83]:
arr =np.arange(15)
print (arr.reshape(5,3).shape)

(5, 3)


In [84]:
print (arr.reshape(5,-1).shape)#利用自动推到

(5, 3)


In [85]:
other_arr = np.ones((3,5))
print (other_arr.shape) #元组

(3, 5)


In [86]:
arr.reshape(other_arr.shape)#利用其它的形状，reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

高维数组可以用ravel来拉平

In [87]:
 arr.ravel().shape

(15,)

连接两个二维数组

In [88]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
print (arr1,"\n\n",arr2)

[[1 2 3]
 [4 5 6]] 

 [[ 7  8  9]
 [10 11 12]]


In [89]:
np.concatenate([arr1,arr2],axis=0)#0维连接在一起

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [91]:
np.vstack((arr1,arr2))#垂直上下

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [92]:
np.hstack((arr1,arr2)) #水平

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

拆分数组

In [93]:
arr = np.random.rand(5,5)
print (arr)

[[ 0.86060796  0.45112857  0.20864796  0.49797319  0.98404927]
 [ 0.62463725  0.19573576  0.53328018  0.30069987  0.95530299]
 [ 0.42617858  0.62642061  0.38103138  0.53820771  0.90373958]
 [ 0.96660694  0.3379231   0.91064805  0.80188289  0.95120523]
 [ 0.01884149  0.28337762  0.9332416   0.13005766  0.15536965]]


In [97]:
first,second,third = np.split(arr,[1,3],axis=0) #在第一个位置和第三个位置截取
print (first,'\n\n',second,'\n\n',third)

[[ 0.86060796  0.45112857  0.20864796  0.49797319  0.98404927]] 

 [[ 0.62463725  0.19573576  0.53328018  0.30069987  0.95530299]
 [ 0.42617858  0.62642061  0.38103138  0.53820771  0.90373958]] 

 [[ 0.96660694  0.3379231   0.91064805  0.80188289  0.95120523]
 [ 0.01884149  0.28337762  0.9332416   0.13005766  0.15536965]]


堆叠辅助

In [98]:
...

Ellipsis

切片直接转化为数组

In [101]:
np.c_[1:6,-5:0]


array([[ 1, -5],
       [ 2, -4],
       [ 3, -3],
       [ 4, -2],
       [ 5, -1]])

使用repeat来重复

In [102]:
arr = np.arange(3)
print (arr)

[0 1 2]


In [103]:
print (arr.repeat([2,3,5]))

[0 0 1 1 1 2 2 2 2 2]


按照元素来重复，制定axis来重复

In [105]:
arr = np.random.rand(2,3)
print (arr)

[[ 0.69469745  0.28780682  0.71313967]
 [ 0.35294584  0.95356549  0.89894023]]


In [109]:
print(arr.repeat(2,axis=1))

[[ 0.69469745  0.69469745  0.28780682  0.28780682  0.71313967  0.71313967]
 [ 0.35294584  0.35294584  0.95356549  0.95356549  0.89894023  0.89894023]]


tile:参考贴瓷砖

In [108]:
print(arr)
print()
print(np.tile(arr,2))

[[ 0.69469745  0.28780682  0.71313967]
 [ 0.35294584  0.95356549  0.89894023]]

[[ 0.69469745  0.28780682  0.71313967  0.69469745  0.28780682  0.71313967]
 [ 0.35294584  0.95356549  0.89894023  0.35294584  0.95356549  0.89894023]]


Numpy输入输出

In [110]:
#读取csv文件作为数组
arr = np.loadtxt('array_ex.txt',delimiter=",") #去读文件，分隔符“，”

FileNotFoundError: [Errno 2] No such file or directory: 'array_ex.txt'

In [112]:
#数据文件读取
arr = np.arange(50).reshape(2,5,5)
print (arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [113]:
np.save('some_array',arr)

In [114]:
arr2 = np.load('some_array.npy')
print (arr2)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [116]:
arr3 = np.arange(15).reshape(3,5)
np.savez('array_archive.npz',arr=arr,b=arr2,c=arr3) #多个存入一个文件

In [118]:
arch = np.load('array_archive.npz')
print (arch['arr'])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [119]:
arch['c']

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

numpy写一个softmax

- 计算exponential
- 按行求和
- 每一行都要除以计算的和

In [121]:
m = np.random.rand(10,10) * 10 + 1000
print (m)

[[ 1004.24791872  1003.55986502  1005.91732549  1004.80652533
   1004.86217717  1008.43317527  1002.48723142  1007.1211634   1005.32305369
   1007.62982446]
 [ 1004.93774917  1001.15423353  1007.37031892  1008.19568567
   1003.09593957  1007.97365681  1004.60711846  1001.40675689
   1006.12669954  1000.39250662]
 [ 1008.27241404  1006.97947157  1002.19545103  1008.04942291
   1002.13032063  1003.36550175  1007.26746149  1004.47086869
   1008.60217098  1006.84241479]
 [ 1004.32011731  1007.27920247  1009.57883925  1002.52711455
   1002.99671181  1007.19716624  1005.80772927  1006.99893769
   1002.94690777  1006.41607962]
 [ 1000.97566433  1006.73110236  1009.27530509  1006.10128326
   1008.97106338  1001.58066415  1001.98363775  1006.35864616
   1002.10090208  1007.96565962]
 [ 1009.01237316  1002.1942741   1008.30704437  1006.43163151
   1007.45445389  1008.12548293  1005.06688803  1002.38246906
   1000.10017634  1001.89705789]
 [ 1004.59109864  1005.96684649  1001.37589756  1004.53621

In [125]:
# np.exp(m)
m_row_max = m.max(axis=1).reshape(10,1)
print (m_row_max, m_row_max.shape) #获取每一行的最大值

[[-0.57919789]
 [-1.03871635]
 [ 0.62373113]
 [ 0.97666827]
 [ 0.67313411]
 [ 0.57919789]
 [-2.22883918]
 [-0.33165195]
 [ 0.29766199]
 [ 0.684145  ]] (10, 1)


In [126]:
m = m - m_row_max
print (m)

[[-3.60605867 -4.05662276 -2.10564761 -4.19311604 -3.83393004  0.
  -3.57730106 -1.4166417  -3.40778358 -1.48749581]
 [-2.45670976 -6.00273579 -0.19313571 -0.34443724 -5.14064918  0.
  -0.99789556 -6.67152974 -2.14461926 -8.26529519]
 [-0.78449235 -1.83994522 -7.03045108 -2.15314747 -7.76871559 -6.27060253
   0.         -5.26986541 -1.3315953  -3.47783449]
 [-5.08972623 -1.89315146  0.         -8.02839296 -7.25526155 -2.79187518
  -1.81266936 -3.09473355 -7.33979565 -4.2571068 ]
 [-8.13064505 -2.13771742  0.         -4.1506901  -0.97737582 -8.10484312
  -5.33322673 -3.43149093 -7.88226718 -2.40399264]
 [ 0.         -6.58060946 -0.8743245  -3.72640563 -2.40004908 -1.46608811
  -2.15604022 -7.31373181 -9.7890567  -8.37865815]
 [-1.61323745  0.         -4.99743424 -2.81378236 -3.45075743 -0.43355334
  -3.20111321 -0.24443344 -6.69812936 -7.37075635]
 [-4.57516979 -2.63570784  0.         -0.13018432 -7.73676688 -7.56193
  -1.3134275  -5.38452266 -5.66092033 -6.05308885]
 [-4.73124457 -1.67

In [128]:
m_exp = np.exp(m)
print(m_exp,m_exp.shape)

[[  2.71586775e-02   1.73073716e-02   1.21766791e-01   1.50991620e-02
    2.16244634e-02   1.00000000e+00   2.79510346e-02   2.42527131e-01
    3.31145147e-02   2.25937739e-01]
 [  8.57165153e-02   2.47198011e-03   8.24370089e-01   7.08619026e-01
    5.85388827e-03   1.00000000e+00   3.68654437e-01   1.26645991e-03
    1.17112618e-01   2.57292963e-04]
 [  4.56351307e-01   1.58826126e-01   8.84532698e-04   1.16118104e-01
    4.22755911e-04   1.89108880e-03   1.00000000e+00   5.14430288e-03
    2.64055678e-01   3.08741971e-02]
 [  6.15970598e-03   1.50596461e-01   1.00000000e+00   3.26071797e-04
    7.06447582e-04   6.13061458e-02   1.63217868e-01   4.52870774e-02
    6.49183167e-04   1.41632202e-02]
 [  2.94378250e-04   1.17923707e-01   1.00000000e+00   1.57535412e-02
    3.76297276e-01   3.02072615e-04   4.82846471e-03   3.23386900e-02
    3.77376505e-04   9.03564710e-02]
 [  1.00000000e+00   1.38700372e-03   4.17143705e-01   2.40792302e-02
    9.07135005e-02   2.30826690e-01   1.15782

In [130]:
m_exp_row_sum = m_exp.sum(axis=1).reshape(10,1)
print (m_exp_row_sum,m_exp_row_sum.shape)

[[ 1.73248689]
 [ 3.11432231]
 [ 2.03456809]
 [ 1.44241218]
 [ 1.63847198]
 [ 1.88088492]
 [ 2.77162539]
 [ 2.24017648]
 [ 1.35485991]
 [ 2.43299089]] (10, 1)


In [132]:
m_softmax = m_exp /m_exp_row_sum
print (m_softmax)

[[  1.56761230e-02   9.98990051e-03   7.02843942e-02   8.71531098e-03
    1.24817473e-02   5.77204947e-01   1.61334755e-02   1.39987860e-01
    1.91138617e-02   1.30412381e-01]
 [  2.75233283e-02   7.93745755e-04   2.64702882e-01   2.27535546e-01
    1.87966681e-03   3.21097145e-01   1.18373887e-01   4.06656662e-04
    3.76045271e-02   8.26160358e-05]
 [  2.24298862e-01   7.80638045e-02   4.34752074e-04   5.70726065e-02
    2.07786563e-04   9.29479237e-04   4.91504808e-01   2.52844960e-03
    1.29784635e-01   1.51748163e-02]
 [  4.27042011e-03   1.04405983e-01   6.93283108e-01   2.26060069e-04
    4.89768175e-04   4.25025153e-02   1.13156191e-01   3.13967658e-02
    4.50067724e-04   9.81912134e-03]
 [  1.79666332e-04   7.19717568e-02   6.10324750e-01   9.61477609e-03
    2.29663541e-01   1.84362393e-04   2.94693152e-03   1.97371029e-02
    2.30322221e-04   5.51467906e-02]
 [  5.31664637e-01   7.37420830e-04   2.21780556e-01   1.28020752e-02
    4.82291604e-02   1.22722388e-01   6.15575